import "./globals.css";
import "../styles/fonts.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex items-center justify-center">{children}</body>
      </html>
    </ClerkProvider>
  );
}
